// This file is auto-generated by @hey-api/openapi-ts

import type { UseMutationOptions } from '@tanstack/vue-query';

import { detectEdges, detectEdgesJson, type Options, uploadFloorplan } from '../sdk.gen';
import type { DetectEdgesData, DetectEdgesError, DetectEdgesJsonData, DetectEdgesJsonError, DetectEdgesJsonResponse, DetectEdgesResponse, UploadFloorplanData, UploadFloorplanError, UploadFloorplanResponse } from '../types.gen';

/**
 * Detect edges in a floorplan image
 *
 * Process a floorplan image to detect edges using Canny edge detection
 */
export const detectEdgesMutation = (options?: Partial<Options<DetectEdgesData>>): UseMutationOptions<DetectEdgesResponse, DetectEdgesError, Options<DetectEdgesData>> => {
    const mutationOptions: UseMutationOptions<DetectEdgesResponse, DetectEdgesError, Options<DetectEdgesData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await detectEdges({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Detect edges using JSON request with base64 image
 *
 * Process a floorplan image (provided as base64) to detect edges
 */
export const detectEdgesJsonMutation = (options?: Partial<Options<DetectEdgesJsonData>>): UseMutationOptions<DetectEdgesJsonResponse, DetectEdgesJsonError, Options<DetectEdgesJsonData>> => {
    const mutationOptions: UseMutationOptions<DetectEdgesJsonResponse, DetectEdgesJsonError, Options<DetectEdgesJsonData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await detectEdgesJson({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Upload a floorplan image
 *
 * Upload a floorplan image (PNG, JPG, JPEG) and return the detected rooms
 */
export const uploadFloorplanMutation = (options?: Partial<Options<UploadFloorplanData>>): UseMutationOptions<UploadFloorplanResponse, UploadFloorplanError, Options<UploadFloorplanData>> => {
    const mutationOptions: UseMutationOptions<UploadFloorplanResponse, UploadFloorplanError, Options<UploadFloorplanData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await uploadFloorplan({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
