// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/vue-query';

import { client } from '../client.gen';
import { getWs, type Options, uploadFloorplan } from '../sdk.gen';
import type { GetWsData, UploadFloorplanData, UploadFloorplanResponse } from '../types.gen';

/**
 * Upload a floorplan PDF/Image for processing
 */
export const uploadFloorplanMutation = (options?: Partial<Options<UploadFloorplanData>>): UseMutationOptions<UploadFloorplanResponse, DefaultError, Options<UploadFloorplanData>> => {
    const mutationOptions: UseMutationOptions<UploadFloorplanResponse, DefaultError, Options<UploadFloorplanData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await uploadFloorplan({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getWsQueryKey = (options?: Options<GetWsData>) => createQueryKey('getWs', options);

/**
 * WebSocket connection for real-time updates
 *
 * Connects to the real-time hub. Supports `subscribe` messages.
 */
export const getWsOptions = (options?: Options<GetWsData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getWsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getWs({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getWsQueryKey(options)
});
