// This file is auto-generated by @hey-api/openapi-ts

export { detectEdges, detectEdgesJson, type Options, uploadFloorplan } from './sdk.gen';
export type { ClientOptions, DetectEdgesData, DetectEdgesError, DetectEdgesErrors, DetectEdgesJsonData, DetectEdgesJsonError, DetectEdgesJsonErrors, DetectEdgesJsonResponse, DetectEdgesJsonResponses, DetectEdgesResponse, DetectEdgesResponses, HandlerEdgeDetectionResponse, UploadFloorplanData, UploadFloorplanError, UploadFloorplanErrors, UploadFloorplanResponse, UploadFloorplanResponses } from './types.gen';
