// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { DebugCropData, DebugCropErrors, DebugCropResponses, GetWsData, UploadFloorplanData, UploadFloorplanErrors, UploadFloorplanResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Upload a floorplan PDF/Image for processing
 */
export const uploadFloorplan = <ThrowOnError extends boolean = false>(options?: Options<UploadFloorplanData, ThrowOnError>) => (options?.client ?? client).post<UploadFloorplanResponses, UploadFloorplanErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/upload',
    ...options,
    headers: {
        'Content-Type': null,
        ...options?.headers
    }
});

/**
 * WebSocket connection for real-time updates
 *
 * Connects to the real-time hub. Supports `subscribe` messages.
 */
export const getWs = <ThrowOnError extends boolean = false>(options?: Options<GetWsData, ThrowOnError>) => (options?.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/ws', ...options });

/**
 * Debug endpoint for testing image cropping
 */
export const debugCrop = <ThrowOnError extends boolean = false>(options?: Options<DebugCropData, ThrowOnError>) => (options?.client ?? client).post<DebugCropResponses, DebugCropErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/debug/crop',
    ...options,
    headers: {
        'Content-Type': null,
        ...options?.headers
    }
});
