// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { CropFloorplanData, CropFloorplanErrors, CropFloorplanResponses, DetectEdgesData, DetectEdgesErrors, DetectEdgesJsonData, DetectEdgesJsonErrors, DetectEdgesJsonResponses, DetectEdgesResponses, UploadFloorplanData, UploadFloorplanErrors, UploadFloorplanResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Automatic crop floorplan from paper
 *
 * Detect and crop the floorplan area from a paper document image
 */
export const cropFloorplan = <ThrowOnError extends boolean = false>(options: Options<CropFloorplanData, ThrowOnError>) => (options.client ?? client).post<CropFloorplanResponses, CropFloorplanErrors, ThrowOnError>({
    url: '/api/v1/process/crop',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Detect edges in a floorplan image
 *
 * Process a floorplan image to detect edges using Canny edge detection
 */
export const detectEdges = <ThrowOnError extends boolean = false>(options: Options<DetectEdgesData, ThrowOnError>) => (options.client ?? client).post<DetectEdgesResponses, DetectEdgesErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/v1/process/edges',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Detect edges using JSON request with base64 image
 *
 * Process a floorplan image (provided as base64) to detect edges
 */
export const detectEdgesJson = <ThrowOnError extends boolean = false>(options: Options<DetectEdgesJsonData, ThrowOnError>) => (options.client ?? client).post<DetectEdgesJsonResponses, DetectEdgesJsonErrors, ThrowOnError>({
    url: '/api/v1/process/edges-json',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Upload a floorplan image
 *
 * Upload a floorplan image (PNG, JPG, JPEG) and return the detected rooms
 */
export const uploadFloorplan = <ThrowOnError extends boolean = false>(options: Options<UploadFloorplanData, ThrowOnError>) => (options.client ?? client).post<UploadFloorplanResponses, UploadFloorplanErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/v1/upload',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});
