// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080/' | (string & {});
};

export type HandlerCropFloorplanRequest = {
    /**
     * base64 or data:image/...
     */
    image: string;
    options?: HandlerEdgeDetectionRequest;
};

export type HandlerCropFloorplanResponse = {
    cropped_image?: string;
    message?: string;
};

export type HandlerEdgeDetectionRequest = {
    blur_radius?: number;
    canny_high?: number;
    canny_low?: number;
    resize_max_width?: number;
};

export type HandlerEdgeDetectionResponse = {
    message?: string;
    /**
     * data:image/png;base64,...
     */
    processed_image?: string;
};

export type CropFloorplanData = {
    /**
     * Image and edge detection options
     */
    body: HandlerCropFloorplanRequest;
    path?: never;
    query?: never;
    url: '/api/v1/process/crop';
};

export type CropFloorplanErrors = {
    /**
     * Bad request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Internal server error
     */
    500: {
        [key: string]: string;
    };
};

export type CropFloorplanError = CropFloorplanErrors[keyof CropFloorplanErrors];

export type CropFloorplanResponses = {
    /**
     * Cropped floorplan
     */
    200: HandlerCropFloorplanResponse;
};

export type CropFloorplanResponse = CropFloorplanResponses[keyof CropFloorplanResponses];

export type DetectEdgesData = {
    body: {
        /**
         * Floorplan image file
         */
        file: Blob | File;
        /**
         * Blur radius for preprocessing
         */
        blur_radius?: number;
        /**
         * Canny low threshold
         */
        canny_low?: number;
        /**
         * Canny high threshold
         */
        canny_high?: number;
        /**
         * Maximum width for resizing
         */
        resize_max_width?: number;
    };
    path?: never;
    query?: never;
    url: '/api/v1/process/edges';
};

export type DetectEdgesErrors = {
    /**
     * Bad request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Internal server error
     */
    500: {
        [key: string]: string;
    };
};

export type DetectEdgesError = DetectEdgesErrors[keyof DetectEdgesErrors];

export type DetectEdgesResponses = {
    /**
     * Edge detection result
     */
    200: HandlerEdgeDetectionResponse;
};

export type DetectEdgesResponse = DetectEdgesResponses[keyof DetectEdgesResponses];

export type DetectEdgesJsonData = {
    /**
     * JSON request with image and options
     */
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/v1/process/edges-json';
};

export type DetectEdgesJsonErrors = {
    /**
     * Bad request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Internal server error
     */
    500: {
        [key: string]: string;
    };
};

export type DetectEdgesJsonError = DetectEdgesJsonErrors[keyof DetectEdgesJsonErrors];

export type DetectEdgesJsonResponses = {
    /**
     * Edge detection result with processed image
     */
    200: {
        [key: string]: unknown;
    };
};

export type DetectEdgesJsonResponse = DetectEdgesJsonResponses[keyof DetectEdgesJsonResponses];

export type UploadFloorplanData = {
    body: {
        /**
         * Floorplan image file
         */
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/v1/upload';
};

export type UploadFloorplanErrors = {
    /**
     * Bad request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Internal server error
     */
    500: {
        [key: string]: string;
    };
};

export type UploadFloorplanError = UploadFloorplanErrors[keyof UploadFloorplanErrors];

export type UploadFloorplanResponses = {
    /**
     * Detection results with rooms
     */
    200: {
        [key: string]: unknown;
    };
};

export type UploadFloorplanResponse = UploadFloorplanResponses[keyof UploadFloorplanResponses];
