// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080/api/v1' | (string & {});
};

export type FloorplanResponse = {
    id?: string;
    /**
     * Base64 encoded image data (data:image/png;base64,...)
     */
    image?: string;
    width?: number;
    height?: number;
    rooms?: Array<Room>;
};

export type Room = {
    id?: string;
    name?: string;
    type?: 'OFFICE' | 'MEETING' | 'UNKNOWN';
    /**
     * [x, y, width, height] in pixels relative to the cropped image
     */
    rect?: [
        number,
        number,
        number,
        number
    ];
    status?: 'AVAILABLE' | 'BUSY' | 'OFFLINE';
};

export type UploadFloorplanData = {
    body?: {
        /**
         * The PDF or Image file to process
         */
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/upload';
};

export type UploadFloorplanErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Processing error
     */
    500: unknown;
};

export type UploadFloorplanResponses = {
    /**
     * Successful processing
     */
    200: FloorplanResponse;
};

export type UploadFloorplanResponse = UploadFloorplanResponses[keyof UploadFloorplanResponses];

export type GetWsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ws';
};
